# Generated by Django 5.0.1 on 2024-02-01 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Result",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("genome_name", models.CharField(max_length=50, null=True)),
                ("start_index", models.IntegerField(null=True)),
                ("match_found", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("initiated_on", models.DateTimeField()),
                ("completed_on", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("dna_sequence", models.CharField(max_length=100)),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gingko.result",
                    ),
                ),
            ],
        ),
    ]
